name: Fetch Electrometer Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      # ⚠️ Debug: list Electrometer env vars
      - name: Dump Electrometer env
        run: |
          echo "ELECTROMETERSETTINGS__BASEURL='$ELECTROMETERSETTINGS__BASEURL'"
          echo "ELECTROMETERSETTINGS__LOGINURL='$ELECTROMETERSETTINGS__LOGINURL'"
        # no env here—this step just shows if they're set by the job-level env

      - name: Restore & Build
        run: dotnet build ElektrometerService.sln --configuration Release

      - name: Run fetcher
        env:
          ELECTROMETERSETTINGS__BASEURL:    ${{ secrets.ELECTROMETERSETTINGS__BASEURL }}
          ELECTROMETERSETTINGS__LOGINURL:   ${{ secrets.ELECTROMETERSETTINGS__LOGINURL }}
          ELECTROMETERSETTINGS__USERNAME:   ${{ secrets.ELECTROMETERSETTINGS__USERNAME }}
          ELECTROMETERSETTINGS__PASSWORD:   ${{ secrets.ELECTROMETERSETTINGS__PASSWORD }}
          ELECTROMETERSETTINGS__SYSN:       ${{ secrets.ELECTROMETERSETTINGS__SYSN }}
          ELECTROMETERSETTINGS__STATIONID:  ${{ secrets.ELECTROMETERSETTINGS__STATIONID }}
          DATABASE__CONNECTIONSTRING:       ${{ secrets.DATABASE__CONNECTIONSTRING }}
        run: |
          dotnet run \
            --project ElektrometerService/ElektrometerService.csproj \
            --configuration Release
